#ifndef myoptions_h
#define myoptions_h

/* Generated by myoptions.h generator - v0.8.1 */
/* https://e2002.github.io/docs/myoptions-generator.html?r=71,1,2,4,5,6,7,8,19,42,43,60,62,64,66,70&i=1,2,3,4,15,16,17,34,39,40,44&v=2,15,-1,21,22,27,35,33,5,4,34 */
/* Put this file next to yoRadio.ino and restart Arduino IDE. */

/* !!! Attention !!! */
/* This configuration depends on some additional libraries. Please install them using the library manager: */
/* Adafruit GFX Library, Adafruit ILI9341, XPT2046_Touchscreen */

/* !!! Do not be alarmed, all right, the default values ​​are not included in this file !!! */

#define DSP_MODEL			DSP_ILI9341
#define DSP_HSPI			true
#define TFT_DC			2
#define TFT_CS			15
#define BRIGHTNESS_PIN			21
#define I2S_DOUT			22
#define I2S_BCLK			27
#define I2S_LRC			35
#define TS_MODEL			TS_MODEL_XPT2046
#define TS_CS			33
#define SDC_CS			5
#define LED_BUILTIN			4
#define LIGHT_SENSOR			34
//
//#define L10N_LANGUAGE       EN                /*  Language (EN, RU). More info in yoRadio/locale/displayL10n_(en|ru).h  */
//#define RSSI_DIGIT true
////#define TFT_ROTATE 3 // 270 degrees

//#define DSP_MODEL           DSP_ST7789
//#define DSP_HSPI            true
//#define LED_INVERT          true
//#define TFT_CS              15
//#define TFT_DC              2
//#define TFT_RST             -1
//#define BRIGHTNESS_PIN      21
//#define I2S_DOUT             4
//#define I2S_BCLK            16
//#define I2S_LRC             17
//#define TS_MODEL            TS_MODEL_XPT2046
//#define TS_SPIPINS          25, 39, 32    /* SCK, MISO, MOSI */
//#define TS_CS               33
//#define LIGHT_SENSOR        34
//#define AUTOBACKLIGHT_MAX   1024
//#define SD_VSPI     true
//#define SDC_CS      5
//
//#define ENC_BTNR      22
//#define ENC_BTNL      35
//#define ENC_BTNB      27
//#define ENC_INTERNALPULLUP      true


#endif
